5monkeys/blues

blues/pureftp.py

Make fabric only warn if `pure-pw show` fails, instead of exiting.

pureftp: Fix creating multiple users

---

blues/templates/app/uwsgi/default/web.ini

The uWSGI log files are owned by root by default, unless told to chown them, thus preventing log rotation

uwsgi: Chown logfiles to uid:gid by default

---

blues/templates/app/uwsgi/default/web.ini
blues/templates/uwsgi/uwsgi/default/vassal.ini

Previous PR just added `logfile-chown` to the file in one of the uwsgi configs in application, instead of making it apply everywhere, even though all projects could use it.

uwsgi: Chown logfile for everything

---

blues/application/tasks.py

When sending deploy notifications it would be useful to have both the
old and the new commit listed. This change will make that possible.

app: deploy: Add parameter to return deployed commits

---

blues/debian.py
blues/git.py

Using pty=False breaks now due to Ubuntu adding a line they shouldn't
have to the root's .profile file, causing `stdin: is not a tty`
warnings.

Remove pty=False everywhere

---

blues/debian.py
blues/git.py

This reverts commit cc2c717b4fc3dac3a1cb1938110dc74f04ceab8b, reversing
changes made to a4145e21da4e6adb48820fa911405902f691cb18.
Git doesn't handle having a pty but not an interactive session well.
We'll solve this by setting env.shell in refabric instead.

Revert "Merge pull request #52 from kyrias/pty-fix-master"

---

blues/debian.py
blues/git.py

This reverts commit fd5d69837ddb467b63b9ce3408251d727b9f44c4, reversing
changes made to 1f7d5216ab231f617eae28d86622efe5e138ea21.
Git doesn't handle having a pty but not an interactive session well.
We'll solve this by setting env.shell in refabric instead.

Revert "Merge pull request #46 from kyrias/not-a-tty"

---

blues/neo4j.py

@andreif the password changing mechanism didn't work for me, quite mysteriously actually. I changed it to use the curl option `-u`. This works for me. I also added a message for when the password already works. In the future we might want a `force` flag.

neo4j: Fix password changing mechanism

---

blues/application/deploy.py

This fixes an issue with `system_dependencies` when using ppa if `software-properties-common` is not present.

Fixed issue with ppa

---

blues/git.py
blues/newrelic.py

Basic blueprint to setup New Relic server.
Notify deployments expects you to use a Git Tag for each deployment and builds a changelog between those tags.

Adds newrelic-server setup and newrelic deployment call

---

blues/node.py

Currently, we reinstall npm/bower packages every time we want to deploy any change. This PR will use symlinks to avoid reinstalling the same packages all over again and also will trigger npm/bower install only if corresponding deps files were modified.
Usage example:
```py
changed = app.deploy(force=force)
node.create_symlinks()  # restore symlinks
if changed or force:
django.deploy()
node.install_dependencies(changed=changed or force)
```

Run npm/bower install if package.json/bower.json changed

---

blues/pam_env.py
blues/templates/pam_env/.pam_environment

Add blueprint to generate .env file

---

blues/newrelic.py
blues/ruby.py

This will allow you to use the following combinations, allowing for legacy -v flag where single rows must be used for each install command:
```
ruby:
gems:
- sass -v 3.4.21
- compass -v 1.0.3
ruby:
gems:
- sass:3.4.21
- compass:1.0.3
ruby:
gems:
- sass:3.4.21 compass:1.0.3
ruby:
gems:
- sass compass
ruby:
gems:
- sass
- compass
```

ruby.py legacy support for gem install -v flags

---

blues/django.py

Here is a real world use case:
```
if django.count_new_statics():
compile_static()
django.collectstatic()
```
`django.count_new_statics()` uses `django.collectstatic()` under the
hood, and `django.collectstatic()` is marked with the `@runs_once`
decorator. This means that the `django.collectstatic()` call in the
above example silently no-ops!
This commit simply calls `manage('collectstatic --no-input -n')`
directly in `django.count_new_statics()` instead of calling on
`django.collectstatic()`, fixing the issue.

Fix `django.count_new_statics()` preventing `django.collectstatic()`

---

blues/templates/uwsgi/uwsgi/default/vassal.ini

So that logging can be disabled/configured while keeping the rest of the vassal defaults.

Encapsulate logging settings in a block

---

blues/templates/uwsgi/init/uwsgi.conf

Value of uWSGI's `--emperor` option needs to be quoted if the path contains wildcards. Otherwise the shell will expand it. That's is not what you want.

Bugfix: Fix emperor configuration path

---

blues/solr.py
blues/templates/solr/system/solr.service

- systemd service for solr (for Ubuntu 16.04 support)
- Don't configure startup scripts for solr version is lesser than 4.0.0
The default behaviour is using built-in jetty to run solr. Lesser than
4.0.0 does have a bundled jetty, but the configuration to run it is not
compatible with blues. So just don't try to configure startup scripts
for those versions.

Solr various

---

blues/java.py

Use `default-jdk` on LSB version >= 16.04. At the time of writing this is Java 8.

Java blueprint: Support Ubuntu 16.04

---

blues/templates/uwsgi/system/uwsgi.service
blues/uwsgi.py

- Fix permission of runtime directory to allow uWSGI emperor vassals to create sockets.
- Issue `systemctl daemon-reload` automatically when `uwsgi.service` is updated

uWSGI blueprint: Fixes

---

blues/debian.py
blues/nginx.py

My scenario is that I needed a nginx server to listen on a private interface, but there was no way of getting the ip address of it inside of a nginx site template. This PR provides a way of doing it.
```
>>> debian.get_ipv4_addresses()
{'eth0': '192.168.1.2', 'eth1': '8.8.8.8'}
```
```
server {
listen {{ ipv4_addresses.eth0 }}:443 ssl;
(...)
}
```

nginx: A way of getting IPv4 interfaces with respective addresses
