blues/wkhtmltopdf.py

They're compiled with patched QT. This version doesn't need X/Xvfb to run.

Install wkhtmltox from the pkgs on sourceforge

---

blues/django.py

Latest public alpha has version 1.8a1

[django] Support pre releases with characters in version

---

blues/slack.py

Add support for notifying multiple channels

---

blues/application/tasks.py

app.notify_deploy: Add missing import

---

blues/app.py
blues/application/tasks.py

Add app task for installing pip requirements manually

---

blues/application/tasks.py

It's okay if you want to hit me now.

deploy: Missed importing git_repository_path

---

blues/debian.py
blues/git.py

Remove pty=False everywhere [cherry-picked to master]

---

blues/app.py
blues/application/tasks.py

```py
app.notify_deploy_start()
changed = app.deploy(force=force)
if changed or force:
django.deploy()
app.reload()
app.notify_deploy(commits=changed)
```

Add method to notify before deploy starts

---

blues/haproxy.py

Signed-off-by: Johannes Löthberg <johannes@kyriasis.com>

haproxy: Add reload function

---

blues/haproxy.py
blues/templates/haproxy/haproxy.cfg

Need this in master for sportamore

haproxy: cherry-picked to master

---

blues/postgres.py

This allows control over the pgtune options such as total memory.

postgres: Allow passing options to generate_pgtune_conf.

---

blues/application/deploy.py
blues/application/tasks.py
blues/python.py

```py
changed = app.deploy(force=force, update_pip=True)
```

Enable keeping pip up-to-date

---

blues/slack.py

Added support for multiple slack configs

---

blues/glusterfs.py

Add glusterfs blueprint.

---

blues/newrelic.py

Uses Json.
note. app_name is changed to app_id.

Updates send_deploy_event to api.v2

---

blues/django.py
blues/git.py

Add a task that counts static files to be copied by django's `collectstatic`.

Django: count static

---

blues/postgres.py

Support excluding table data in pg_dump.

---

blues/samba.py
blues/templates/samba/smb.conf

Improved configuration of Samba.

Samba blueprint: Improved configuration

---

.travis.yml
Makefile
blues/application/deploy.py
blues/application/project.py
blues/util.py
requirements.txt
runtests.py
setup.cfg
setup.py
tests/test_requirement_tree.py
tests/test_requirements.py

Support multiple requirements files.

---

blues/maildev.py
blues/templates/maildev/default
blues/templates/maildev/system/maildev.service

MailDev[1] is a tool that makes it easy to view all the e-mail sent by
your application. Useful in development/staging environments.
[1] https://github.com/djfarrelly/MailDev

maildev: Implement MailDev blueprint
